//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspen2eCitation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Users/Public/Documents/FMCSA/Aspen/Data/ASPEN_DATA.FDB;")]
        public string aspenDbLocation {
            get {
                return ((string)(this["aspenDbLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User=SYSDBA;Password=masterkey;DataSource=localhost;Port=3050;Dialect=3;Charset=N" +
            "ONE;Role=;Connection lifetime=15;Pooling=true;MinPoolSize=0;MaxPoolSize=50;Packe" +
            "t Size=8192;ServerType=0;Database=")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\iyeTek\\LESS")]
        public string iyeTekLocation {
            get {
                return ((string)(this["iyeTekLocation"]));
            }
            set {
                this["iyeTekLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Documents\\FMCSA\\Aspen\\Data\\ASPEN_DATA.FDB")]
        public string aspenDbFileLocation {
            get {
                return ((string)(this["aspenDbFileLocation"]));
            }
            set {
                this["aspenDbFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PortableApps\\iyeTek\\System\\iyeTek\\roaming\\modified\\@PROGRAMFILESX86@\\iyeTek\\LE" +
            "SS")]
        public string iyeTekLocation2 {
            get {
                return ((string)(this["iyeTekLocation2"]));
            }
            set {
                this["iyeTekLocation2"] = value;
            }
        }
    }
}
