CREATE TABLE `user` (
  `USER_ID` varchar(25) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `STATE_ID` varchar(2) DEFAULT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `SITE_ID` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`),
  KEY `USER_STATE_SHORTNAME_idx` (`STATE_ID`),
  CONSTRAINT `USER_STATE_SHORTNAME` FOREIGN KEY (`STATE_ID`) REFERENCES `state` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;